[package]
name = "loony-router"
version = "0.1.0"
edition = "2024"

[[bin]]
name="loony-router"
path="./src/main.rs"

[dependencies]
matchit = { workspace = true }
regex.workspace = true
futures-util = { workspace = true }